export const LESSON_CATALOG = [
  {
    id: 'M1L1', module: 1, order: 1,
    title: 'Test de Diagnóstico',
    description: 'Establece tu velocidad base y nivel de comprensión',
    duration: 10,
    icon: '🎯',
    color: 'from-amber-400 to-orange-500',
    technique: 'Medición de WPM + Quiz',
    requiredModule: 1,
  },
  {
    id: 'M1L2', module: 1, order: 2,
    title: 'Marcador de Posición',
    description: 'Un guía visual elimina las regresiones y estabiliza tu ritmo',
    duration: 12,
    icon: '➡️',
    color: 'from-blue-400 to-indigo-500',
    technique: 'Pacing visual',
    requiredModule: 1,
  },
  {
    id: 'M1L3', module: 1, order: 3,
    title: 'El Escudo Anti-Regresión',
    description: 'Bloquea la re-lectura para forzar un procesamiento más atento',
    duration: 12,
    icon: '🛡️',
    color: 'from-green-400 to-emerald-500',
    technique: 'Máscara de regresión',
    requiredModule: 1,
  },
  {
    id: 'M1L4', module: 1, order: 4,
    title: 'Silenciador Interno',
    description: 'Detecta y reduce la subvocalización en palabras funcionales',
    duration: 12,
    icon: '🔇',
    color: 'from-purple-400 to-violet-500',
    technique: 'Detección de subvocalización',
    requiredModule: 1,
  },
  {
    id: 'M1L5', module: 1, order: 5,
    title: 'Tabla de Schulte',
    description: 'Entrena la visión periférica y el span visual',
    duration: 8,
    icon: '🔢',
    color: 'from-pink-400 to-rose-500',
    technique: 'Atención periférica',
    requiredModule: 1,
  },
  {
    id: 'M2L1', module: 2, order: 1,
    title: 'Chunking Semántico',
    description: 'Lee grupos de 3 palabras como una sola unidad de significado',
    duration: 15,
    icon: '📦',
    color: 'from-cyan-400 to-teal-500',
    technique: 'RSVP en bloques',
    requiredModule: 2,
  },
  {
    id: 'M2L2', module: 2, order: 2,
    title: 'RSVP con ORP',
    description: 'Presenta palabras con el punto óptimo de reconocimiento centrado',
    duration: 15,
    icon: '⚡',
    color: 'from-red-400 to-rose-500',
    technique: 'Optimal Recognition Point',
    requiredModule: 2,
  },
  {
    id: 'M2L3', module: 2, order: 3,
    title: 'Schulte Avanzado + Periférico',
    description: 'Detecta palabras periféricas sin mover los ojos del centro',
    duration: 14,
    icon: '👁️',
    color: 'from-fuchsia-400 to-purple-500',
    technique: 'Span visual periférico',
    requiredModule: 2,
  },
  {
    id: 'M2L4', module: 2, order: 4,
    title: 'Indentación Periférica',
    description: 'Aprende a capturar los bordes de cada línea sin fijar la vista',
    duration: 12,
    icon: '↔️',
    color: 'from-lime-400 to-green-500',
    technique: 'Márgenes de entrenamiento',
    requiredModule: 2,
  },
  {
    id: 'M2L5', module: 2, order: 5,
    title: 'Pre-Lectura Estructural',
    description: 'Activa tu mapa mental antes de leer para mejorar la comprensión',
    duration: 15,
    icon: '🗺️',
    color: 'from-orange-400 to-amber-500',
    technique: 'T.H.I.E.V.E.S.',
    requiredModule: 2,
  },
  {
    id: 'M3L1', module: 3, order: 1,
    title: 'Sprint Intervals',
    description: 'Burst training: alterna sprints a alta velocidad con recuperación',
    duration: 18,
    icon: '🏃',
    color: 'from-red-500 to-orange-500',
    technique: 'Over-speed training',
    requiredModule: 3,
  },
  {
    id: 'M3L2', module: 3, order: 2,
    title: 'Modo Unidireccional',
    description: 'Cero regresiones: la pantalla solo avanza, nunca retrocede',
    duration: 15,
    icon: '⏩',
    color: 'from-blue-500 to-cyan-500',
    technique: 'Flujo forzado',
    requiredModule: 3,
  },
  {
    id: 'M3L3', module: 3, order: 3,
    title: 'Wide Angle Reading',
    description: 'Chunks de 4-5 palabras: la técnica de los lectores expertos',
    duration: 18,
    icon: '🔭',
    color: 'from-indigo-500 to-purple-500',
    technique: 'Lectura de ángulo amplio',
    requiredModule: 3,
  },
  {
    id: 'M3L4', module: 3, order: 4,
    title: 'Control de Subvocalización',
    description: 'A 400 WPM tu voz interna no puede seguir el ritmo. Entrénalo.',
    duration: 15,
    icon: '🤫',
    color: 'from-violet-500 to-fuchsia-500',
    technique: 'Silenciador cognitivo',
    requiredModule: 3,
  },
  {
    id: 'M3L5', module: 3, order: 5,
    title: 'Simulacro con Presión',
    description: 'Lee y comprende bajo presión temporal controlada',
    duration: 15,
    icon: '⏱️',
    color: 'from-rose-500 to-pink-500',
    technique: 'Arousal óptimo',
    requiredModule: 3,
  },
  {
    id: 'M4L1', module: 4, order: 1,
    title: 'Anotación Mental',
    description: 'Construye un mapa mental mientras lees a alta velocidad',
    duration: 20,
    icon: '🧠',
    color: 'from-teal-500 to-green-500',
    technique: 'Lectura activa',
    requiredModule: 4,
  },
  {
    id: 'M4L2', module: 4, order: 2,
    title: 'Textos Propios',
    description: 'Importa cualquier artículo o texto para entrenarte con material real',
    duration: 20,
    icon: '📄',
    color: 'from-sky-500 to-blue-500',
    technique: 'Transferencia de habilidades',
    requiredModule: 4,
  },
  {
    id: 'M4L3', module: 4, order: 3,
    title: 'Repetición Espaciada',
    description: 'Consolida lo aprendido con el algoritmo SM-2 de Anki',
    duration: 5,
    icon: '🔄',
    color: 'from-amber-500 to-yellow-500',
    technique: 'SuperMemo-2',
    requiredModule: 4,
  },
  {
    id: 'M4L4', module: 4, order: 4,
    title: 'Certificación SprintRead',
    description: '≥500 WPM + ≥70% comprensión en texto desconocido. ¿Listo?',
    duration: 20,
    icon: '🏆',
    color: 'from-yellow-400 to-amber-500',
    technique: 'Evaluación sumativa',
    requiredModule: 4,
  },
];

export const MODULE_INFO = [
  { id: 1, title: 'Fundamentos', subtitle: 'Elimina los frenos mecánicos', wpmRange: '150–260 WPM', weeks: '2 semanas', gateWpm: 260, gateComp: 75 },
  { id: 2, title: 'Expansión Visual', subtitle: 'Amplía tu campo de visión', wpmRange: '260–380 WPM', weeks: '3 semanas', gateWpm: 360, gateComp: 70 },
  { id: 3, title: 'Velocidad', subtitle: 'Supera tus límites', wpmRange: '380–480 WPM', weeks: '3 semanas', gateWpm: 450, gateComp: 65 },
  { id: 4, title: 'Maestría', subtitle: 'Consolida y certifica', wpmRange: '480–550+ WPM', weeks: '4 semanas', gateWpm: 500, gateComp: 70 },
];
